### ISSUE TITLE
update antd

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-patter-js#11]
To avoid the need to request fonts for icons.

(new version uses svg)

**Comment by bochaco** [comment]
`antd` was already upgraded to `v3.9.2` with PR #8, and according to antd [changelog `svg` icons were introduced in v0.9.0](https://github.com/ant-design/ant-design/blob/HEAD/CHANGELOG.en-US.md#390), so I'll check if fonts are not being pulled and close this.

**Comment by bochaco** [comment]
It seems that effectively fonst are not being fetched anymore, I can now only see a `css` fetch from the site `http://localhost:2345/src.7ed060e2.css` but I don't see fonts being pulled like before, e.g. `http://localhost:38047/dummy/iconfont.woff` and `https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.woff`

I'm closing it @joshuef , let's re-open it if we see an issue when removing the hack for the fonts from the browser.
